name: fedi_match
description: "Dating for the Fediverse"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  appinio_swiper: ^2.1.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_chat_ui: ^1.6.13
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.15.0
  http: ^1.2.1
  pointycastle: ^3.9.1
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
